---
- name: Testing andrewrothstein.luajit
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'luajit -v'
      ansible.builtin.command: luajit -v
      changed_when: false
      register: luajit_test_output
    - name: Output from 'luajit -v'
      ansible.builtin.debug:
        msg: '{{ luajit_test_output.stdout }}'
