---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/luajit -v
      register: luajit_test_output
    - debug:
        msg: '{{ luajit_test_output.stdout }}'
  
