---
# tasks file for luajit
- name: look for luajit installation at {{ luajit_target_exe }}
  become: yes
  stat:
    path: '{{ luajit_target_exe }}'
  changed_when: False
  register: luajit_binary
- when: not luajit_binary.stat.exists
  block:
    - name: downloading {{ luajit_tgz }}...
      become: '{{ luajit_escalate }}'
      become_user: root
      get_url:
        url: '{{ luajit_url }}'
        checksum: '{{ luajit_checksum }}'
        dest: '{{ luajit_tmp_tgz }}'
        mode: 0644
    - name: mkdir {{ luajit_parent_srcs_dir }}
      become: '{{ luajit_escalate }}'
      become_user: root
      file:
        path: '{{ luajit_parent_srcs_dir }}'
        state: directory
        mode: 0755
    - name: unarchiving {{ luajit_tmp_tgz }} to {{ luajit_parent_srcs_dir }}...
      become: '{{ luajit_escalate }}'
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ luajit_tmp_tgz }}'
        dest: '{{ luajit_parent_srcs_dir }}'
        creates: '{{ luajit_src_root_dir }}'
    - name: building in {{ luajit_src_root_dir }}...
      become: '{{ luajit_escalate }}'
      become_user: root
      command: make
      args:
        chdir: '{{ luajit_src_root_dir }}'
        creates: '{{ luajit_src_root_dir }}/src/luajit'
    - name: installing from {{ luajit_src_root_dir }}...
      become: '{{ luajit_escalate }}'
      become_user: root
      command: make install
      args:
        chdir: '{{ luajit_src_root_dir }}'
        creates: '{{ luajit_target_exe }}'
  always:
    - name: destroying {{ luajit_src_root_dir }} and {{ luajit_tmp_tgz }}...
      become: '{{ luajit_escalate }}'
      become_user: root
      with_items:
        - '{{ luajit_src_root_dir }}'
        - '{{ luajit_tmp_tgz }}'
      file:
        path: '{{ item }}'
        state: absent
