---
# tasks file for luajit
- name: download tgz...
  get_url: url='{{luajit_url}}' dest='/tmp/{{luajit_tgz}}'

- name: unarchiving to /opt...
  unarchive: copy=no src='/tmp/{{luajit_tgz}}' dest='/opt'

- name: building...
  command: make
  args:
    chdir: /opt/{{luajit_name}}
    creates: /opt/{{luajit_name}}/src/luajit

- name: installing...
  command: make install
  args:
    chdir: /opt/{{luajit_name}}
    creates: /usr/local/bin/luajit

- name: destroying luajit src....
  when: luajit_destroy_src
  file: path='{{item}}' state=absent
  with_items:
    - '/opt/{{luajit_name}}'
    - '/tmp/{{luajit_tgz}}'
  